# Generated by Django 5.2.10 on 2026-01-11 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Data da sessão')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora fim')),
                ('summary', models.TextField(verbose_name='Resumo / Evolução')),
                ('plan_next', models.TextField(blank=True, default='', verbose_name='Plano para próxima sessão')),
                ('family_guidance', models.TextField(blank=True, default='', verbose_name='Orientações para família')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_notes', to='patients.patient', verbose_name='Paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_notes', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
    ]
