# Generated by Django 5.2.10 on 2026-01-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnote',
            name='session_type',
            field=models.CharField(choices=[('ABA', 'ABA'), ('AT', 'Acompanhante Terapêutico (AT)'), ('FONO', 'Fonoaudiologia'), ('PSICO', 'Psicologia'), ('PSICOPED', 'Psicopedagogia'), ('NEURO', 'Neuropsicologia'), ('OUTRO', 'Outro')], default='ABA', max_length=20, verbose_name='Tipo de sessão'),
        ),
    ]
