# Generated by Django 5.2.10 on 2026-01-11 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_sessionnote_session_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('file', models.FileField(upload_to='records/attachments/%Y/%m/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='records.sessionnote', verbose_name='Prontuário')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo do prontuário',
                'verbose_name_plural': 'Anexos do prontuário',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
